-- Jezleen Security V5 - Supabase (opcional)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null,
  description text not null,
  price text default 'Consultar precio',
  image text,
  pdf text,
  featured boolean default false,
  active boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.products enable row level security;
create policy "public can read active products" on public.products for select using (active = true);
-- Para administración real, crea un usuario en Supabase Auth y añade políticas para authenticated.
create policy "authenticated can manage products" on public.products for all to authenticated using (true) with check (true);
